### PR TITLE
2N methods are really not FSAL anymore

### LINKED ISSUE #1279: continuous callbacks are broken for LowStorageRK2NCache
When #1278 is merged, discrete callbacks using `resize!` are fine for `LowStorageRK2NCache`. However, continuous callbacks are not:
```julia
julia> using Revise, Test, OrdinaryDiffEq, DiffEqCallbacks

julia> function f(du, u, p, t)
           du .= u
           nothing
       end
f (generic function with 1 method)

julia> u0 = ones(2)

julia> function affect!(integrator)
         u = integrator.u
         resize!(integrator, length(u) + 1)
         u .= 1
         u_modified!(integrator, true)
         nothing
       end
affect! (generic function with 1 method)

julia> condition_continuous(u, t, integrator) = t - 1
condition (generic function with 1 method)

julia> callback_continuous = ContinuousCallback(condition_continuous, affect!);

julia> condition_discrete(u, t, integrator) = isapprox(t, 1)
condition (generic function with 1 method)

julia> callback_discrete = DiscreteCallback(condition_discrete, affect!);

julia> tspan = (0.0, 2.0)
(0.0, 2.0)

julia> prob = ODEProblem(f, u0, tspan)
ODEProblem with uType Array{Float64,2} and tType Float64. In-place: true
timespan: (0.0, 2.0)
u0: [1.0 1.0; 1.0 1.0]

julia> sol = solve(prob, RK4(), dt=0.125, adaptive=false, callback=callback_continuous)

julia> @test all(sol[end] .== sol[end][1])

julia> sol = solve(prob, CarpenterKennedy2N54(williamson_condition=false), dt=0.125, adaptive=false, callback=callback_continuous)

julia> @test all(sol[end] .== sol[end][1])

julia> sol = solve(prob, CarpenterKennedy2N54(williamson_condition=false), dt=0.125, adaptive=false, callback=callback_discrete)

julia> @test all(sol[end] .== sol[end][1])
```

Note that 
```julia
julia> sol = solve(prob, CarpenterKennedy2N54(williamson_condition=false), dt=0.125, adaptive=false, callback=callback_continuous)
retcode: Success
Interpolation: 3rd order Hermite
t: 18-element Array{Float64,1}:
 0.0
 ...
 1.0
 1.0
 ...
 2.0
u: 18-element Array{Array{Float64,1},1}:
 [1.0, 1.0]
 ...
 [3.2178781198404143, 3.2178781198404143]
 [1.0, 1.0, 1.0]
  ...
 [3.2178781198404143, 3.2178781198404143, 3.2178781198404143]
```
gives wrong solution values `u` just before the continuous callback is applied at `t == 1` (it should be `u[1] ≈ 2.718 ≈  exp(1)`).

### PR DESCRIPTION
**Pull request by ranocha**
This closes #1279. Moreover, it makes the methods more efficient if they are used together with callbacks modifying `u`, e.g. adaptive mesh refinement in Trixi.jl.

### CODE REVIEW

**Comment by ranocha** [comment]
From my point of view, we can close #1281 once this PR is merged.

File: test/integrators/ode_cache_tests.jl [hunk 1]
```diff
@@ -108,10 +108,35 @@ end
...
+
+# additional cache tests to find more bugs
+println("Enforced adaptive dt checks")
+u0_adapt = zeros(2)
+f_adapt = (du, u, p, t) -> du .= t
+prob_adapt = ODEProblem(f_adapt, u0_adapt, (0.0, 2.0))
+condition_adapt = (u, t, integrator) -> true
+affect!_adapt = function (integrator)
+  dt = rand((0.0625, 0.125, 0.25))
+  set_proposed_dt!(integrator, dt)
```
Comment (ChrisRackauckas) [inline test/integrators/ode_cache_tests.jl:127]: nice yeah, this is a pretty good test case to run a bunch of stuff through.
