### PR TITLE
Fix nested ForwardDiff through Rosenbrock solve (#3486)

### LINKED ISSUE #3486: Second order differentiation of `solve` with ForwardDiff errors due to incorrect types in `JacReuseState`
MWE:

```julia
julia> using OrdinaryDiffEqRosenbrock

julia> using SciMLBase: ODEProblem

julia> using ForwardDiff

julia> rhs_oop(u, p, t) = [-p[1] * u[1] * u[1]];

julia> function loss(p)
           prob = ODEProblem{false}(rhs_oop, [1.0], (0.0, p[2]), p)
           sol = solve(prob, Rodas5P())
           return only(last(sol.u))
       end;

julia> ForwardDiff.gradient(loss, [1.0, 1.0])
2-element Vector{Float64}:
 -0.2500005148461045
 -0.2500001490614758

julia> ForwardDiff.hessian(loss, [1.0, 1.0])
ERROR: MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(loss), Float64}, Float64, 2})
The type `Float64` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat
   @ Base rounding.jl:265
  (::Type{T})(::T) where T<:Number
   @ Core boot.jl:965
  Float64(::IrrationalConstants.Sqrt3)
   @ IrrationalConstants ~/.julia/packages/IrrationalConstants/RokwY/src/macro.jl:111
  ...

Stacktrace:
  [1] convert(::Type{Float64}, x::ForwardDiff.Dual{ForwardDiff.Tag{typeof(loss), Float64}, Float64, 2})
    @ Base ./number.jl:7
  [2] setproperty!(x::OrdinaryDiffEqRosenbrock.JacReuseState{Float64}, f::Symbol, v::ForwardDiff.Dual{ForwardDiff.Tag{typeof(loss), Float64}, Float64, 2})
    @ Base ./Base_compiler.jl:57
  [3] calc_rosenbrock_differentiation(integrator::OrdinaryDiffEqCore.ODEIntegrator{…}, cache::OrdinaryDiffEqRosenbrock.RosenbrockCombinedConstantCache{…}, dtgamma::ForwardDiff.Dual{…}, repeat_step::Bool)
    @ OrdinaryDiffEqDifferentiation ~/.julia/packages/OrdinaryDiffEqDifferentiation/5UyhR/src/derivative_utils.jl:922
  [4] perform_step!(integrator::OrdinaryDiffEqCore.ODEIntegrator{…}, cache::OrdinaryDiffEqRosenbrock.RosenbrockCombinedConstantCache{…}, repeat_step::Bool)
    @ OrdinaryDiffEqRosenbrock ~/.julia/packages/OrdinaryDiffEqRosenbrock/pUxeg/src/rosenbrock_perform_step.jl:468
  [5] perform_step!
    @ ~/.julia/packages/OrdinaryDiffEqRosenbrock/pUxeg/src/rosenbrock_perform_step.jl:456 [inlined]
  [6] solve!(integrator::OrdinaryDiffEqCore.ODEIntegrator{…})
    @ OrdinaryDiffEqCore ~/.julia/packages/OrdinaryDiffEqCore/AvUKo/src/solve.jl:889
  [7] #__solve#58
    @ ~/.julia/packages/OrdinaryDiffEqCore/AvUKo/src/solve.jl:10 [inlined]
  [8] __solve
    @ ~/.julia/packages/OrdinaryDiffEqCore/AvUKo/src/solve.jl:1 [inlined]
  [9] #solve_call#22
    @ ~/.julia/packages/DiffEqBase/CJTzr/src/solve.jl:172 [inlined]
 [10] solve_call
    @ ~/.julia/packages/DiffEqBase/CJTzr/src/solve.jl:137 [inlined]
 [11] #solve_up#29
    @ ~/.julia/packages/DiffEqBase/CJTzr/src/solve.jl:646 [inlined]
 [12] solve_up
    @ ~/.julia/packages/DiffEqBase/CJTzr/src/solve.jl:619 [inlined]
 [13] #solve#28
    @ ~/.julia/packages/DiffEqBase/CJTzr/src/solve.jl:603 [inlined]
 [14] solve
    @ ~/.julia/packages/DiffEqBase/CJTzr/src/solve.jl:591 [inlined]
 [15] loss(p::Vector{ForwardDiff.Dual{ForwardDiff.Tag{typeof(loss), Float64}, ForwardDiff.Dual{ForwardDiff.Tag{typeof(loss), Float64}, Float64, 2}, 2}})
    @ Main ./REPL[10]:3
 [16] vector_mode_dual_eval!
    @ ~/.julia/packages/ForwardDiff/z3jRk/src/apiutils.jl:24 [inlined]
 [17] vector_mode_gradient(f::typeof(loss), x::Vector{ForwardDiff.Dual{…}}, cfg::ForwardDiff.GradientConfig{ForwardDiff.Tag{…}, ForwardDiff.Dual{…}, 2, Vector{…}})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/z3jRk/src/gradient.jl:98
 [18] gradient
    @ ~/.julia/packages/ForwardDiff/z3jRk/src/gradient.jl:20 [inlined]
 [19] #hessian##0
    @ ~/.julia/packages/ForwardDiff/z3jRk/src/hessian.jl:17 [inlined]
 [20] vector_mode_dual_eval!
    @ ~/.julia/packages/ForwardDiff/z3jRk/src/apiutils.jl:24 [inlined]
 [21] vector_mode_jacobian(f::ForwardDiff.var"#hessian##0#hessian##1"{…}, x::Vector{…}, cfg::ForwardDiff.JacobianConfig{…})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/z3jRk/src/jacobian.jl:129
 [22] jacobian
    @ ~/.julia/packages/ForwardDiff/z3jRk/src/jacobian.jl:22 [inlined]
 [23] hessian
    @ ~/.julia/packages/ForwardDiff/z3jRk/src/hessian.jl:18 [inlined]
 [24] hessian(f::typeof(loss), x::Vector{Float64}, cfg::ForwardDiff.HessianConfig{ForwardDiff.Tag{typeof(loss), Float64}, Float64, 2, Vector{ForwardDiff.Dual{…}}, Vector{ForwardDiff.Dual{…}}})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/z3jRk/src/hessian.jl:15
 [25] hessian(f::typeof(loss), x::Vector{Float64})
    @ ForwardDiff ~/.julia/packages/ForwardDiff/z3jRk/src/hessian.jl:15
 [26] top-level scope
    @ REPL[12]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

```julia
julia> versioninfo()
Julia Version 1.12.6
Commit 15346901f00 (2026-04-09 19:20 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 10 × Apple M2 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m2)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 6 virtual cores)
Environment:
  JULIA_PKG_USE_CLI_GIT = true
  JULIA_PKG_PRESERVE_TIERED_INSTALLED = true
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE = true

(jl_d4aGG9) pkg> st --manifest
Status `/private/var/folders/n6/98_7bm0j0hb57zv3l3tj8sxh0000gn/T/jl_d4aGG9/Manifest.toml`
  [47edcb42] ADTypes v1.21.0
  [7d9f7c33] Accessors v0.1.44
  [79e6a3ab] Adapt v4.5.2
  [4fba245c] ArrayInterface v7.24.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [70df07ce] BracketingNonlinearSolve v1.12.1
  [2a0fbf3d] CPUSummary v0.2.7
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [38540f10] CommonSolve v0.2.6
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.18.1
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.6.0
  [adafc99b] CpuId v0.3.1
  [864edb3b] DataStructures v0.19.4
  [2b5f629d] DiffEqBase v6.218.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.7.16
  [ffbed154] DocStringExtensions v0.9.5
  [4e289a0a] EnumX v1.0.7
  [f151be2c] EnzymeCore v0.8.19
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7034ab61] FastBroadcast v1.3.1
  [9aa1b823] FastClosures v0.3.2
  [a4df4552] FastPower v1.3.1
  [6a86dc24] FiniteDiff v2.30.0
  [f6369f11] ForwardDiff v1.3.3
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v1.5.0
  [46192b85] GPUArraysCore v0.2.0
  [615f187c] IfElse v0.1.1
  [3587e190] InverseFunctions v0.1.17
  [92d709cd] IrrationalConstants v0.2.6
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.7.1
  [ae98c720] Jieko v0.2.1
  [ba0b0d4f] Krylov v0.10.6
  [10f19ff3] LayoutPointers v0.1.17
  [7ed4a6bd] LinearSolve v3.75.0
  [2ab3a3ac] LogExpFunctions v0.3.29
  [e6f89c97] LoggingExtras v1.2.0
  [1914dd2f] MacroTools v0.5.16
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.4
  [2e0e35c7] Moshi v0.3.7
  [46d2c3a1] MuladdMacro v0.2.4
  [77ba4419] NaNMath v1.1.3
  [be0214bd] NonlinearSolveBase v2.25.0
  [bac558e1] OrderedCollections v1.8.1
  [bbf590c4] OrdinaryDiffEqCore v3.33.0
  [4302a76b] OrdinaryDiffEqDifferentiation v2.9.0
  [43230ef6] OrdinaryDiffEqRosenbrock v1.31.0
  [f517fe37] Polyester v0.7.19
  [1d0040c9] PolyesterWeave v0.2.2
  [d236fae5] PreallocationTools v1.2.0
  [aea7be01] PrecompileTools v1.3.3
  [21216c6a] Preferences v1.5.2 [loaded: v1.5.1]
  [3cdcf5f2] RecipesBase v1.3.4
⌅ [731186ca] RecursiveArrayTools v3.54.0
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.1
  [7e49a35a] RuntimeGeneratedFunctions v0.5.18
  [94e857df] SIMDTypes v0.1.0
⌅ [0bca4576] SciMLBase v2.155.0
  [19f34311] SciMLJacobianOperators v0.1.13
  [a6db7da4] SciMLLogging v1.9.1
  [c0aeaf25] SciMLOperators v1.16.0
  [431bcebd] SciMLPublic v1.0.1
  [53ae85a6] SciMLStructures v1.10.0
  [efcf1570] Setfield v1.1.2
  [0a514795] SparseMatrixColorings v0.4.27
  [276daf66] SpecialFunctions v2.7.2
  [aedffcd0] Static v1.3.1
  [0d7ed370] StaticArrayInterface v1.9.0
  [1e83bf80] StaticArraysCore v1.4.4
  [10745b16] Statistics v1.11.1
  [7792a7ef] StrideArraysCore v0.5.8
  [2efcf032] SymbolicIndexingInterface v0.3.46
  [8290d209] ThreadingUtilities v0.5.5
  [a759f4b9] TimerOutputs v0.5.29
  [781d530d] TruncatedStacktraces v1.4.0
  [1d5cc7b8] IntelOpenMP_jll v2025.2.0+0
  [856f044c] MKL_jll v2025.2.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [1317d2d5] oneTBB_jll v2022.0.0+1
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.7.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [ac6e5ff7] JuliaSyntaxHighlighting v1.12.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.12.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [ca575930] NetworkOptions v1.3.0
  [44cfe95a] Pkg v1.12.1
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.12.0
  [f489334b] StyledStrings v1.11.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.3.0+1
  [deac9b47] LibCURL_jll v8.15.0+0
  [e37daf67] LibGit2_jll v1.9.0+0
  [29816b5a] LibSSH2_jll v1.11.3+1
  [14a3606d] MozillaCACerts_jll v2025.11.4
  [4536629a] OpenBLAS_jll v0.3.29+0
  [05823500] OpenLibm_jll v0.8.7+0
  [458c3c95] OpenSSL_jll v3.5.4+0
  [bea87d4a] SuiteSparse_jll v7.8.3+2
  [83775a58] Zlib_jll v1.3.1+2
  [8e850b90] libblastrampoline_jll v5.15.0+0
  [8e850ede] nghttp2_jll v1.64.0+1
  [3f19e933] p7zip_jll v17.7.0+0
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

AFAICT the problem is once again an unconditional use of `ForwardDiff.value` in https://github.com/SciML/OrdinaryDiffEq.jl/blob/d921e476f364639c2835b7261cd16e99e39ee2c3/lib/OrdinaryDiffEqDifferentiation/src/derivative_utils.jl#L22

Unconditional use of `ForwardDiff.value` is almost always incorrect but often the bug only surfaces in higher-order differentiation. Basically, one must perform unwrapping conditional on and only for the currently active tag (ie., use `ForwardDiff.value(T, x)` instead of `ForwardDiff.value(x)` where `T` is the tag of the currently active differentiation) as otherwise `ForwardDiff.Dual`s that are actually constant wrt to the current differentiation are unwrapped even though these `Dual`s must be treated as primal values.

### PR DESCRIPTION
**Pull request by ChrisRackauckas-Claude**
## Summary

Closes #3486. `ForwardDiff.hessian` through a `Rodas5P()` (and other Rosenbrock-W) solve errored with:

```
MethodError: no method matching Float64(::ForwardDiff.Dual{...})
  ... setproperty!(x::OrdinaryDiffEqRosenbrock.JacReuseState{Float64}, f::Symbol,
                   v::ForwardDiff.Dual{...})
  ... calc_rosenbrock_differentiation(...)
```

### Root cause

`JacReuseState{T}` was constructed with `T = Float64` (from `zero(dt)` at cache-build time), and `derivative_utils.jl` assigned `jac_reuse.pending_dtgamma = ForwardDiff.value(dtgamma)` before storing. Under `ForwardDiff.hessian`, `dtgamma` is a nested `Dual{OuterTag, Dual{InnerTag, Float64, N}, N}`; one `ForwardDiff.value` strips only the outer layer, leaving a `Dual{InnerTag, Float64, N}` that cannot be stored in the `::Float64` field.

As the issue points out, unconditional `ForwardDiff.value` is also unsafe in principle: for the currently-active tag it collapses a still-live derivative into a primal.

### Fix

Per the issue author's suggested approach: make `JacReuseState` store the dtgamma values verbatim and remove the unwrapping.

- `JacReuseState{T}` → untyped `JacReuseState`, with `last_dtgamma::Any` / `pending_dtgamma::Any`. The other fields (`cached_J/dT/W`) were already `::Any`, so this matches existing practice in the struct.
- `_jac_reuse_value(x) = ForwardDiff.value(x)` → `_jac_reuse_value(x) = x`. Kept as an identity shim rather than deleted so the two call sites and any external callers see a stable API; it can be fully removed as a follow-up.

The reuse-decision logic only uses `iszero(·)`, ratios, and `abs(dtgamma / last − 1) > tol` comparisons — all well-defined on Duals (ForwardDiff compares primal values) — so no downstream changes are needed.

### Reproducer from the issue

```julia
using OrdinaryDiffEqRosenbrock, SciMLBase, ForwardDiff
rhs_oop(u, p, t) = [-p[1] * u[1] * u[1]]
function loss(p)
    prob = ODEProblem{false}(rhs_oop, [1.0], (0.0, p[2]), p)
    sol = solve(prob, Rodas5P())
    return only(last(sol.u))
end

ForwardDiff.gradient(loss, [1.0, 1.0])  # worked before, still works
ForwardDiff.hessian(loss, [1.0, 1.0])   # errored before, works now
```

On this branch (Julia 1.11):

```
┌ Info: hessian
│   H =
│    2×2 Matrix{Float64}:
│      0.249999    -1.53084e-6
└     -1.53084e-6   0.249983
```

## Test plan

- [x] Ran the exact MWE from #3486 locally — gradient and hessian both succeed with finite values.
- [x] Verified unfixed `master` still errors on the same MWE (confirmed reproducer).
- [x] Ran `lib/OrdinaryDiffEqRosenbrock/test/dae_rosenbrock_ad_tests.jl` on Julia 1.11 — all 8 existing AD test configurations (IIP/OOP × Brown/Shampine × ForwardDiff/FiniteDiff × Rodas5P/Tsit5DA) still pass, plus the new `Second-order ForwardDiff through solve (issue #3486)` testset (2/2).
- [x] Quick plain-Float64 Lotka-Volterra smoke test to ensure non-AD path still converges and is fast.
- [ ] CI green across the Rosenbrock / Differentiation matrices.

Added a regression test in `lib/OrdinaryDiffEqRosenbrock/test/dae_rosenbrock_ad_tests.jl` that exercises exactly the failing Hessian-through-solve pattern.

### CODE REVIEW

**Comment by devmotion** [comment]
I think in addition to the unconditional use of `ForwardDiff.value`, another problem here is https://github.com/ChrisRackauckas-Claude/OrdinaryDiffEq.jl/blob/a747ca88eb790eae53d85014dd11bccb0aac64be/lib/OrdinaryDiffEqRosenbrock/src/rosenbrock_caches.jl#L469: It seems in all other Rosenbrock caches the first argument is set to `zero(dt)`.

**Comment by ChrisRackauckas** [comment]
ForwardDiff.value is fine in this context since there isn't really a reason to differentiate the jacobian reuse controller: it results in a boolean which is not a differentiable quantity anyways. However, it's not really optimizing much, and making it recurse the removal is probably harder than just figuring out how to push the quantity all the way through.

File: lib/OrdinaryDiffEqRosenbrock/src/rosenbrock_caches.jl [hunk 1]
```diff
@@ -457,11 +470,15 @@ function alg_cache(
     else
         interp_order = H_rows
     end
+    # Seed JacReuseState with `zero(dt)` so its dtgamma fields carry the full
+    # (possibly ForwardDiff.Dual) type dtgamma will have at solve time.
+    # `constvalue(uBottomEltypeNoUnits)` unconditionally strips Duals, which is
+    # wrong under nested AD (e.g. `ForwardDiff.hessian` through solve).
```
Comment (ChrisRackauckas) [inline lib/OrdinaryDiffEqRosenbrock/src/rosenbrock_caches.jl]:
```suggestion
```

File: lib/OrdinaryDiffEqRosenbrock/test/dae_rosenbrock_ad_tests.jl [hunk 2]
```diff
@@ -62,3 +64,23 @@ sol = @inferred solve(
...
+#   MethodError: no method matching Float64(::ForwardDiff.Dual{...})
+# ...when the Jacobian-reuse state tried to unwrap one Dual level via
+# `ForwardDiff.value(dtgamma)` and assign it to a strictly-typed `::Float64`
+# field. Unconditional unwrapping collapses the still-active inner derivative,
+# so the fix stores `dtgamma` verbatim (Dual and all) in `JacReuseState`.
+@testset "Second-order ForwardDiff through solve (issue #3486)" begin
+    rhs_oop_simple(u, p, t) = [-p[1] * u[1] * u[1]]
+    function loss_oop(p)
+        prob = ODEProblem{false}(rhs_oop_simple, [1.0], (0.0, p[2]), p)
+        sol = solve(prob, Rodas5P())
```
Comment (devmotion) [inline lib/OrdinaryDiffEqRosenbrock/test/dae_rosenbrock_ad_tests.jl]: Probably would be useful to test other Rosenbrock methods and inplace problems as well, to ensure all paths are covered

Comment (ChrisRackauckas) [reply lib/OrdinaryDiffEqRosenbrock/test/dae_rosenbrock_ad_tests.jl]: They are all using the same solver path except Rosenbrock23 (which is then changing in the very near future)

Comment (devmotion) [reply lib/OrdinaryDiffEqRosenbrock/test/dae_rosenbrock_ad_tests.jl]: IIRC the example did not error with in-place formulation since that was already using `zero(dt)` when constructing the cache (combined with the unconditional unwrapping it meant that in the in-place case the unwrapped `Number` was promoted to a `Dual` with zero partials, so the cache just zeroed out the partials).
