### PR TITLE
Make internal nlsolve use possibly-smaller chunksize, distinct from ODE chunksize

### LINKED ISSUE #3157: Mass-matrix DAE with specified ForwardDiff chunksize errors when initial condition not satisfied
**Describe the bug 🐞**

For mass-matrix DAE solve with unsatisfiable constraint, a specified ForwardDiff chunk size equal to problem size results in a ForwardDiff error. Based on the CI runs where this showed up (parameter fitting on ODE, where bad parameter guesses are possible), it seems to be a change in the last month or so.

**Expected behavior**

An `InitialFailure` retcode or other similar graceful error handling, as occurs when the ForwardDiff chunk size is not specified.

**Minimal Reproducible Example 👇**

```julia
using OrdinaryDiffEqRosenbrock, OrdinaryDiffEqNonlinearSolve
using ADTypes
using LinearAlgebra: Diagonal
function dae(du, u, p, t)
    du[1] = u[2]
    du[2] = exp(u[1]) + exp(u[2])
    return nothing
end
dae_func = ODEFunction(dae, mass_matrix=Diagonal([1.0, 0.0]))
prob = ODEProblem(dae_func, [0.0, 1.0], (0.0, 1.0))
solve(prob, Rodas5P()) # runs, returns an InitialFailure retcode
solve(prob, Rodas5P(autodiff=AutoForwardDiff(chunksize=2))) # errors
```

**Error & Stacktrace ⚠️**

```julia
ERROR: ArgumentError: chunk size cannot be greater than ForwardDiff.structural_length(x) (2 > 1)
Stacktrace:
  [1] chunk_mode_jacobian(f!::DifferentiationInterface.FixTail{…}, y::Vector{…}, x::Vector{…}, cfg::ForwardDiff.JacobianConfig{…})
    @ ForwardDiff C:\Users\iwheeler\.julia\packages\ForwardDiff\egQMG\src\jacobian.jl:173
  [2] jacobian
    @ C:\Users\iwheeler\.julia\packages\ForwardDiff\egQMG\src\jacobian.jl:42 [inlined]
  [3] jacobian
    @ C:\Users\iwheeler\.julia\packages\DifferentiationInterface\afUhd\ext\DifferentiationInterfaceForwardDiffExt\twoarg.jl:471 [inlined]
  [4] construct_jacobian_cache(prob::NonlinearProblem{…}, alg::GeneralizedFirstOrderAlgorithm{…}, f::NonlinearFunction{…}, fu::Vector{…}, u::Vector{…}, p::SciMLBase.NullParameters; stats::SciMLBase.NLStats, autodiff::AutoForwardDiff{…}, vjp_autodiff::AutoFiniteDiff{…}, jvp_autodiff::AutoForwardDiff{…}, linsolve::Nothing)
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\jacobian.jl:77
  [5] construct_jacobian_cache
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\jacobian.jl:33 [inlined]
  [6] __init(::NonlinearProblem{…}, ::GeneralizedFirstOrderAlgorithm{…}; stats::SciMLBase.NLStats, alias::SciMLBase.NonlinearAliasSpecifier, maxiters::Int64, abstol::Float64, reltol::Float64, maxtime::Nothing, termination_condition::Nothing, internalnorm::typeof(NonlinearSolveBase.L2_NORM), verbose::NonlinearVerbosity{…}, linsolve_kwargs::@NamedTuple{}, initializealg::NonlinearSolveBase.NonlinearSolveDefaultInit, kwargs::@Kwargs{…})
    @ NonlinearSolveFirstOrder C:\Users\iwheeler\.julia\packages\NonlinearSolveFirstOrder\hAPzw\src\solve.jl:193
  [7] __init
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveFirstOrder\hAPzw\src\solve.jl:134 [inlined]
  [8] __solve(::NonlinearProblem{…}, ::GeneralizedFirstOrderAlgorithm{…}; kwargs::@Kwargs{…})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:299
  [9] macro expansion
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:548 [inlined]
 [10] __generated_polysolve(::NonlinearProblem{…}, ::NonlinearSolvePolyAlgorithm{…}; stats::SciMLBase.NLStats, alias::SciMLBase.NonlinearAliasSpecifier, verbose::NonlinearVerbosity{…}, initializealg::NonlinearSolveBase.NonlinearSolveDefaultInit, kwargs::@Kwargs{…})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:485
 [11] __generated_polysolve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:485 [inlined]
 [12] #__solve#165
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:453 [inlined]
 [13] __solve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:449 [inlined]
 [14] #solve_call#149
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:174 [inlined]
 [15] solve_call
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:140 [inlined]
 [16] #solve_up#148
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:135 [inlined]
 [17] solve_up
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:120 [inlined]
 [18] #solve#147
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:92 [inlined]
 [19] _initialize_dae!(integrator::OrdinaryDiffEqCore.ODEIntegrator{…}, prob::ODEProblem{…}, alg::BrownFullBasicInit{…}, isinplace::Val{…})
    @ OrdinaryDiffEqNonlinearSolve C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqNonlinearSolve\VssNh\src\initialize_dae.jl:635
 [20] _default_dae_init!
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqNonlinearSolve\VssNh\src\initialize_dae.jl:130 [inlined]
 [21] _initialize_dae!
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\initialize_dae.jl:39 [inlined]
 [22] initialize_dae! (repeats 2 times)
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\initialize_dae.jl:20 [inlined]
 [23] _ode_init(prob::ODEProblem{…}, alg::Rodas5P{…}, timeseries_init::Tuple{}, ts_init::Tuple{}, ks_init::Tuple{}; saveat::Tuple{}, tstops::Tuple{}, d_discontinuities::Tuple{}, save_idxs::Nothing, save_everystep::Bool, save_on::Bool, save_discretes::Bool, save_start::Bool, save_end::Nothing, callback::Nothing, dense::Bool, calck::Bool, dt::Nothing, dtmin::Float64, dtmax::Float64, force_dtmin::Bool, adaptive::Bool, abstol::Nothing, reltol::Nothing, gamma::Nothing, qmin::Nothing, qmax::Nothing, qsteady_min::Nothing, qsteady_max::Nothing, beta1::Nothing, beta2::Nothing, qoldinit::Nothing, fullnormalize::Bool, failfactor::Int64, maxiters::Int64, internalnorm::typeof(DiffEqBase.ODE_DEFAULT_NORM), internalopnorm::typeof(LinearAlgebra.opnorm), isoutofdomain::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), unstable_check::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), verbose::Standard, controller::Nothing, timeseries_errors::Bool, dense_errors::Bool, advance_to_tstop::Bool, stop_at_next_tstop::Bool, initialize_save::Bool, progress::Bool, progress_steps::Int64, progress_name::String, progress_message::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), progress_id::Symbol, userdata::Nothing, allow_extrapolation::Bool, initialize_integrator::Bool, alias::ODEAliasSpecifier, initializealg::DiffEqBase.DefaultInit, rng::Nothing, save_noise::Bool, delta::Nothing, W::Nothing, P::Nothing, sqdt::Nothing, noise::Nothing, c::Nothing, rate_constants::Nothing, _cache::Nothing, _u::Nothing, _uprev::Nothing, seed::UInt64, kwargs::@Kwargs{})
    @ OrdinaryDiffEqCore C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\solve.jl:766
 [24] _ode_init
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\solve.jl:47 [inlined]
 [25] #__init#59
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\solve.jl:37 [inlined]
 [26] __init (repeats 2 times)
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\solve.jl:19 [inlined]
 [27] #__solve#58
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\solve.jl:9 [inlined]
 [28] __solve
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\q5Gdj\src\solve.jl:1 [inlined]
 [29] #solve_call#22
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\4RFWW\src\solve.jl:172 [inlined]
 [30] solve_call
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\4RFWW\src\solve.jl:137 [inlined]
 [31] solve_up(prob::ODEProblem{…}, sensealg::Nothing, u0::Vector{…}, p::SciMLBase.NullParameters, args::Rodas5P{…}; originator::SciMLBase.ChainRulesOriginator, kwargs::@Kwargs{})
    @ DiffEqBase C:\Users\iwheeler\.julia\packages\DiffEqBase\4RFWW\src\solve.jl:630
 [32] solve_up
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\4RFWW\src\solve.jl:603 [inlined]
 [33] #solve#28
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\4RFWW\src\solve.jl:587 [inlined]
 [34] solve(prob::ODEProblem{…}, args::Rodas5P{…})
    @ DiffEqBase C:\Users\iwheeler\.julia\packages\DiffEqBase\4RFWW\src\solve.jl:575
 [35] top-level scope
    @ c:\Users\iwheeler\.julia\dev\LyoPronto\test\mwe.jl:14
```

Non-abbreviated stacktrace:
<details><summary>Details</summary>
<p>
ArgumentError: chunk size cannot be greater than ForwardDiff.structural_length(x) (2 > 1)
Stacktrace:
  [1] chunk_mode_jacobian(f!::DifferentiationInterface.FixTail{NonlinearFunction{true, SciMLBase.FullSpecialize, OrdinaryDiffEqNonlinearSolve.var"#_initialize_dae!##18#_initialize_dae!##19"{Type{ForwardDiff.Dual}, Bool, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, Vector{Float64}, Vector{Bool}, Float64, Vector{Bool}, Nothing}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing}, Tuple{SciMLBase.NullParameters}}, y::Vector{Float64}, x::Vector{Float64}, cfg::ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}}})
    @ ForwardDiff C:\Users\iwheeler\.julia\packages\ForwardDiff\egQMG\src\jacobian.jl:173
  [2] jacobian
    @ C:\Users\iwheeler\.julia\packages\ForwardDiff\egQMG\src\jacobian.jl:42 [inlined]
  [3] jacobian
    @ C:\Users\iwheeler\.julia\packages\DifferentiationInterface\afUhd\ext\DifferentiationInterfaceForwardDiffExt\twoarg.jl:471 [inlined]
  [4] construct_jacobian_cache(prob::NonlinearProblem{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}, true, SciMLBase.NullParameters, NonlinearFunction{true, SciMLBase.FullSpecialize, OrdinaryDiffEqNonlinearSolve.var"#_initialize_dae!##18#_initialize_dae!##19"{Type{ForwardDiff.Dual}, Bool, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, Vector{Float64}, Vector{Bool}, Float64, Vector{Bool}, Nothing}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardNonlinearProblem, Nothing, Nothing}, alg::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, Missing, NonlinearSolveBase.NewtonDescent{Nothing}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, AutoFiniteDiff{Val{:forward}, Val{:forward}, Val{:hcentral}, Nothing, Nothing, Bool}, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Val{false}}, f::NonlinearFunction{true, SciMLBase.FullSpecialize, OrdinaryDiffEqNonlinearSolve.var"#_initialize_dae!##18#_initialize_dae!##19"{Type{ForwardDiff.Dual}, Bool, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, Vector{Float64}, Vector{Bool}, Float64, Vector{Bool}, Nothing}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing}, fu::Vector{Float64}, u::Vector{Float64}, p::SciMLBase.NullParameters; stats::SciMLBase.NLStats, autodiff::AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, vjp_autodiff::AutoFiniteDiff{Val{:forward}, Val{:forward}, Val{:hcentral}, Nothing, Nothing, Bool}, jvp_autodiff::AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, linsolve::Nothing)
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\jacobian.jl:77
  [5] construct_jacobian_cache
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\jacobian.jl:33 [inlined]
  [6] __init(::NonlinearProblem{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}, true, SciMLBase.NullParameters, NonlinearFunction{true, SciMLBase.FullSpecialize, OrdinaryDiffEqNonlinearSolve.var"#_initialize_dae!##18#_initialize_dae!##19"{Type{ForwardDiff.Dual}, Bool, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, Vector{Float64}, Vector{Bool}, Float64, Vector{Bool}, Nothing}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardNonlinearProblem, Nothing, Nothing}, ::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, Missing, NonlinearSolveBase.NewtonDescent{Nothing}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, Nothing, Val{false}}; stats::SciMLBase.NLStats, alias::SciMLBase.NonlinearAliasSpecifier, maxiters::Int64, abstol::Float64, reltol::Float64, maxtime::Nothing, termination_condition::Nothing, internalnorm::typeof(NonlinearSolveBase.L2_NORM), verbose::NonlinearSolveBase.NonlinearVerbosity{SciMLLogging.None, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent}, linsolve_kwargs::@NamedTuple{}, initializealg::NonlinearSolveBase.NonlinearSolveDefaultInit, kwargs::@Kwargs{alias_u0::Bool})
    @ NonlinearSolveFirstOrder C:\Users\iwheeler\.julia\packages\NonlinearSolveFirstOrder\hAPzw\src\solve.jl:193
  [7] __init
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveFirstOrder\hAPzw\src\solve.jl:134 [inlined]
  [8] __solve(::NonlinearProblem{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}, true, SciMLBase.NullParameters, NonlinearFunction{true, SciMLBase.FullSpecialize, OrdinaryDiffEqNonlinearSolve.var"#_initialize_dae!##18#_initialize_dae!##19"{Type{ForwardDiff.Dual}, Bool, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, Vector{Float64}, Vector{Bool}, Float64, Vector{Bool}, Nothing}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardNonlinearProblem, Nothing, Nothing}, ::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, Missing, NonlinearSolveBase.NewtonDescent{Nothing}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, Nothing, Val{false}}; kwargs::@Kwargs{stats::SciMLBase.NLStats, alias_u0::Bool, verbose::NonlinearSolveBase.NonlinearVerbosity{SciMLLogging.None, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent}, abstol::Float64, reltol::Float64})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:299
  [9] macro expansion
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:548 [inlined]
 [10] __generated_polysolve(::NonlinearProblem{SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}, true, SciMLBase.NullParameters, NonlinearFunction{true, SciMLBase.FullSpecialize, OrdinaryDiffEqNonlinearSolve.var"#_initialize_dae!##18#_initialize_dae!##19"{Type{ForwardDiff.Dual}, Bool, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, PreallocationTools.DiffCache{Vector{Float64}, Vector{Float64}}, Vector{Float64}, Vector{Bool}, Float64, Vector{Bool}, Nothing}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardNonlinearProblem, Nothing, Nothing}, ::NonlinearSolveBase.NonlinearSolvePolyAlgorithm{Val{6}, Tuple{NonlinearSolveQuasiNewton.QuasiNewtonAlgorithm{Nothing, Missing, NonlinearSolveBase.NewtonDescent{Nothing}, NonlinearSolveQuasiNewton.GoodBroydenUpdateRule, NonlinearSolveQuasiNewton.NoChangeInStateReset{Nothing}, NonlinearSolveQuasiNewton.IdentityInitialization{Nothing, NonlinearSolveQuasiNewton.FullStructure}, Val{false}}, NonlinearSolveQuasiNewton.QuasiNewtonAlgorithm{Nothing, Missing, NonlinearSolveBase.NewtonDescent{Nothing}, NonlinearSolveQuasiNewton.KlementUpdateRule, NonlinearSolveQuasiNewton.IllConditionedJacobianReset, NonlinearSolveQuasiNewton.IdentityInitialization{Nothing, NonlinearSolveQuasiNewton.DiagonalStructure}, Val{false}}, NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, Missing, NonlinearSolveBase.NewtonDescent{Nothing}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, Nothing, Val{false}}, NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, NonlinearSolveFirstOrder.GenericTrustRegionScheme{NonlinearSolveFirstOrder.RadiusUpdateSchemes.__Simple, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}}, NonlinearSolveBase.Dogleg{NonlinearSolveBase.NewtonDescent{Nothing}, NonlinearSolveBase.SteepestDescent{Nothing}}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, Nothing, Val{false}}, NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, NonlinearSolveFirstOrder.GenericTrustRegionScheme{NonlinearSolveFirstOrder.RadiusUpdateSchemes.__Bastin, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}, Rational{Int64}}, NonlinearSolveBase.Dogleg{NonlinearSolveBase.NewtonDescent{Nothing}, NonlinearSolveBase.SteepestDescent{Nothing}}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, Nothing, Val{false}}, NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{Missing, NonlinearSolveFirstOrder.LevenbergMarquardtTrustRegion{Float64}, NonlinearSolveBase.GeodesicAcceleration{NonlinearSolveBase.DampedNewtonDescent{Nothing, Float64, NonlinearSolveFirstOrder.LevenbergMarquardtDampingFunction{Float64, Float64, Float64}}, Float64, Float64}, Nothing, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, Nothing, Val{true}}}}; stats::SciMLBase.NLStats, alias::SciMLBase.NonlinearAliasSpecifier, verbose::NonlinearSolveBase.NonlinearVerbosity{SciMLLogging.None, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent}, initializealg::NonlinearSolveBase.NonlinearSolveDefaultInit, kwargs::@Kwargs{abstol::Float64, reltol::Float64})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:485
 [11] __generated_polysolve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:485 [inlined]
 [12] #__solve#165
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:453 [inlined]
 [13] __solve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:449 [inlined]
 [14] #solve_call#149
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:174 [inlined]
 [15] solve_call
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:140 [inlined]
 [16] #solve_up#148
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:135 [inlined]
 [17] solve_up
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:120 [inlined]
 [18] #solve#147
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:92 [inlined]
 [19] _initialize_dae!(integrator::OrdinaryDiffEqCore.ODEIntegrator{Rodas5P{2, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, true, Vector{Float64}, Nothing, Float64, SciMLBase.NullParameters, Float64, Float64, Float64, Float64, Vector{Vector{Float64}}, ODESolution{Float64, 2, Vector{Vector{Float64}}, Nothing, Nothing, Vector{Float64}, Vector{Vector{Vector{Float64}}}, Nothing, ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardODEProblem}, Rodas5P{2, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, OrdinaryDiffEqCore.InterpolationData{ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Vector{Float64}}, Vector{Float64}, Vector{Vector{Vector{Float64}}}, Nothing, OrdinaryDiffEqRosenbrock.RosenbrockCache{Vector{Float64}, Vector{Float64}, Float64, Vector{Float64}, Matrix{Float64}, Matrix{Float64}, OrdinaryDiffEqRosenbrock.RodasTableau{Float64, Float64}, SciMLBase.TimeGradientWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, SciMLBase.NullParameters}, SciMLBase.UJacobianWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Float64, SciMLBase.NullParameters}, LinearSolve.LinearCache{Matrix{Float64}, Vector{Float64}, Vector{Float64}, SciMLBase.NullParameters, LinearSolve.DefaultLinearSolver, LinearSolve.DefaultLinearSolverInit{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Vector{Int64}}, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Vector{Int64}}, Nothing, Nothing, Nothing, LinearAlgebra.SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int32}}, Base.RefValue{Int32}}, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Base.RefValue{Int64}}, LinearAlgebra.QRPivoted{Float64, Matrix{Float64}, Vector{Float64}, Vector{Int64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Matrix{Float64}, Vector{Float64}}, LinearSolve.InvPreconditioner{Diagonal{Float64, Vector{Float64}}}, Diagonal{Float64, Vector{Float64}}, Float64, LinearSolve.LinearVerbosity{SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent}, Bool, LinearSolve.LinearSolveAdjoint{Missing}}, Tuple{DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgJacobianPrep{Nothing, ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}}}, Tuple{}}, DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgJacobianPrep{Nothing, ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}}}, Tuple{}}}, Tuple{DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgDerivativePrep{Tuple{SciMLBase.TimeGradientWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, SciMLBase.NullParameters}, Vector{Float64}, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Float64, Tuple{}}, Float64, ForwardDiff.DerivativeConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}, Tuple{}}, DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgDerivativePrep{Tuple{SciMLBase.TimeGradientWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, SciMLBase.NullParameters}, Vector{Float64}, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Float64, Tuple{}}, Float64, ForwardDiff.DerivativeConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}, Tuple{}}}, Float64, Rodas5P{2, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, BitVector}, SciMLBase.DEStats, Nothing, Nothing, Nothing, Nothing}, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, OrdinaryDiffEqRosenbrock.RosenbrockCache{Vector{Float64}, Vector{Float64}, Float64, Vector{Float64}, Matrix{Float64}, Matrix{Float64}, OrdinaryDiffEqRosenbrock.RodasTableau{Float64, Float64}, SciMLBase.TimeGradientWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, SciMLBase.NullParameters}, SciMLBase.UJacobianWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Float64, SciMLBase.NullParameters}, LinearSolve.LinearCache{Matrix{Float64}, Vector{Float64}, Vector{Float64}, SciMLBase.NullParameters, LinearSolve.DefaultLinearSolver, LinearSolve.DefaultLinearSolverInit{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Vector{Int64}}, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Vector{Int64}}, Nothing, Nothing, Nothing, LinearAlgebra.SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int32}}, Base.RefValue{Int32}}, Tuple{LinearAlgebra.LU{Float64, Matrix{Float64}, Vector{Int64}}, Base.RefValue{Int64}}, LinearAlgebra.QRPivoted{Float64, Matrix{Float64}, Vector{Float64}, Vector{Int64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Matrix{Float64}, Vector{Float64}}, LinearSolve.InvPreconditioner{Diagonal{Float64, Vector{Float64}}}, Diagonal{Float64, Vector{Float64}}, Float64, LinearSolve.LinearVerbosity{SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent}, Bool, LinearSolve.LinearSolveAdjoint{Missing}}, Tuple{DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgJacobianPrep{Nothing, ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}}}, Tuple{}}, DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgJacobianPrep{Nothing, ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 2}}}}, Tuple{}}}, Tuple{DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgDerivativePrep{Tuple{SciMLBase.TimeGradientWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, SciMLBase.NullParameters}, Vector{Float64}, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Float64, Tuple{}}, Float64, ForwardDiff.DerivativeConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}, Tuple{}}, DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgDerivativePrep{Tuple{SciMLBase.TimeGradientWrapper{true, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Vector{Float64}, SciMLBase.NullParameters}, Vector{Float64}, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Float64, Tuple{}}, Float64, ForwardDiff.DerivativeConfig{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}, Tuple{}}}, Float64, Rodas5P{2, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, OrdinaryDiffEqCore.DEOptions{Float64, Float64, Float64, Float64, OrdinaryDiffEqCore.PIController{Float64}, typeof(DiffEqBase.ODE_DEFAULT_NORM), typeof(LinearAlgebra.opnorm), Nothing, CallbackSet{Tuple{}, Tuple{}}, typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), DataStructures.BinaryHeap{Float64, DataStructures.FasterForward}, DataStructures.BinaryHeap{Float64, DataStructures.FasterForward}, Nothing, Nothing, Int64, Tuple{}, Tuple{}, Tuple{}, OrdinaryDiffEqCore.DEVerbosity{SciMLLogging.Minimal, SciMLLogging.Minimal, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.WarnLevel, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent, SciMLLogging.Silent}, Nothing}, Nothing, Float64, Nothing, DiffEqBase.DefaultInit, BitVector, OrdinaryDiffEqCore.PIController{Float64}, Random.TaskLocalRNG, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardODEProblem}, alg::BrownFullBasicInit{Float64, Nothing}, isinplace::Val{true})
    @ OrdinaryDiffEqNonlinearSolve C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqNonlinearSolve\VssNh\src\initialize_dae.jl:635
 [20] _default_dae_init!
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqNonlinearSolve\VssNh\src\initialize_dae.jl:130 [inlined]
 [21] _initialize_dae!
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\initialize_dae.jl:39 [inlined]
 [22] initialize_dae! (repeats 2 times)
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\initialize_dae.jl:20 [inlined]
 [23] _ode_init(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardODEProblem}, alg::Rodas5P{2, AutoForwardDiff{2, ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}, timeseries_init::Tuple{}, ts_init::Tuple{}, ks_init::Tuple{}; saveat::Tuple{}, tstops::Tuple{}, d_discontinuities::Tuple{}, save_idxs::Nothing, save_everystep::Bool, save_on::Bool, save_discretes::Bool, save_start::Bool, save_end::Nothing, callback::Nothing, dense::Bool, calck::Bool, dt::Nothing, dtmin::Float64, dtmax::Float64, force_dtmin::Bool, adaptive::Bool, abstol::Nothing, reltol::Nothing, gamma::Nothing, qmin::Nothing, qmax::Nothing, qsteady_min::Nothing, qsteady_max::Nothing, beta1::Nothing, beta2::Nothing, qoldinit::Nothing, fullnormalize::Bool, failfactor::Int64, maxiters::Int64, internalnorm::typeof(DiffEqBase.ODE_DEFAULT_NORM), internalopnorm::typeof(LinearAlgebra.opnorm), isoutofdomain::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), unstable_check::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), verbose::SciMLLogging.Standard, controller::Nothing, timeseries_errors::Bool, dense_errors::Bool, advance_to_tstop::Bool, stop_at_next_tstop::Bool, initialize_save::Bool, progress::Bool, progress_steps::Int64, progress_name::String, progress_message::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), progress_id::Symbol, userdata::Nothing, allow_extrapolation::Bool, initialize_integrator::Bool, alias::ODEAliasSpecifier, initializealg::DiffEqBase.DefaultInit, rng::Nothing, save_noise::Bool, delta::Nothing, W::Nothing, P::Nothing, sqdt::Nothing, noise::Nothing, c::Nothing, rate_constants::Nothing, _cache::Nothing, _u::Nothing, _uprev::Nothing, seed::UInt64, kwargs::@Kwargs{})
    @ OrdinaryDiffEqCore C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:770
 [24] _ode_init
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:47 [inlined]
 [25] #__init#59
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:37 [inlined]
 [26] __init (repeats 2 times)
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:19 [inlined]
 [27] #__solve#58
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:9 [inlined]
 [28] __solve
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:1 [inlined]
 [29] #solve_call#22
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:172 [inlined]
 [30] solve_call
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:137 [inlined]
 [31] solve_up(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardODEProblem}, sensealg::Nothing, u0::Vector{Float64}, p::SciMLBase.NullParameters, args::Rodas5P{2, AutoForwardDiff{2, Nothing}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)}; originator::SciMLBase.ChainRulesOriginator, kwargs::@Kwargs{})
    @ DiffEqBase C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:630
 [32] solve_up
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:603 [inlined]
 [33] #solve#28
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:587 [inlined]
 [34] solve(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.FullSpecialize, typeof(dae), Diagonal{Float64, Vector{Float64}}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, @Kwargs{}, SciMLBase.StandardODEProblem}, args::Rodas5P{2, AutoForwardDiff{2, Nothing}, Nothing, typeof(OrdinaryDiffEqCore.DEFAULT_PRECS), Val{:forward}(), true, nothing, typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!)})
    @ DiffEqBase C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:575
 [35] top-level scope
    @ REPL[22]:1
 [36] top-level scope
    @ REPL:1

</p>
</details> 

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
[4c88cf16] Aqua v0.8.14
  [c3a54625] JET v0.11.3
  [d3d80556] LineSearches v7.6.0
  [86014da0] LyoPronto v0.3.2 `..`
  [8913a72c] NonlinearSolve v4.16.0
⌃ [36348300] OptimizationOptimJL v0.4.10
  [c4bf5708] SavitzkyGolay v0.9.1
  [84d833dd] TransformVariables v0.8.21
  [9d95f2ec] TypedTables v1.4.6
  [1986cc42] Unitful v1.28.0
  [8dfed614] Test v1.11.0
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
[47edcb42] ADTypes v1.21.0
  [7d9f7c33] Accessors v0.1.43
  [79e6a3ab] Adapt v4.5.0
  [4c88cf16] Aqua v0.8.14
  [dce04be8] ArgCheck v2.5.0
  [4fba245c] ArrayInterface v7.23.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [70df07ce] BracketingNonlinearSolve v1.11.0
  [2a0fbf3d] CPUSummary v0.2.7
  [d360d2e6] ChainRulesCore v1.26.0
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [da1fd8a2] CodeTracking v3.0.0
  [3da002f7] ColorTypes v0.12.1
  [38540f10] CommonSolve v0.2.6
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.18.1
  [807dbc54] Compiler v0.1.1
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.6.0
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [82cc6244] DataInterpolations v8.9.0
  [864edb3b] DataStructures v0.19.3
  [e2d170a0] DataValueInterfaces v1.0.0
  [85a47980] Dictionaries v0.4.6
⌃ [2b5f629d] DiffEqBase v6.210.1
  [459566f4] DiffEqCallbacks v4.12.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.7.16
  [ffbed154] DocStringExtensions v0.9.5
  [4e289a0a] EnumX v1.0.7
  [f151be2c] EnzymeCore v0.8.18
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [a4df4552] FastPower v1.3.1
  [1a297f60] FillArrays v1.16.0
  [64ca27bc] FindFirstFunctions v1.8.0
  [6a86dc24] FiniteDiff v2.29.0
  [53c48c17] FixedPointNumbers v0.8.5
  [f6369f11] ForwardDiff v1.3.2
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [46192b85] GPUArraysCore v0.2.0
  [615f187c] IfElse v0.1.1
  [313cdc1a] Indexing v1.1.1
  [3587e190] InverseFunctions v0.1.17
  [92d709cd] IrrationalConstants v0.2.6
  [82899510] IteratorInterfaceExtensions v1.0.0
  [c3a54625] JET v0.11.3
  [692b3bcd] JLLWrappers v1.7.1
  [ae98c720] Jieko v0.2.1
  [aa1ae85d] JuliaInterpreter v0.10.10
  [70703baa] JuliaSyntax v1.0.2
  [ba0b0d4f] Krylov v0.10.6
  [b964fa9f] LaTeXStrings v1.4.0
  [10f19ff3] LayoutPointers v0.1.17
  [87fe0de2] LineSearch v0.1.6
  [d3d80556] LineSearches v7.6.0
⌃ [7ed4a6bd] LinearSolve v3.65.0
  [2ab3a3ac] LogExpFunctions v0.3.29
  [e6f89c97] LoggingExtras v1.2.0
  [6f1432cf] LoweredCodeUtils v3.5.1
  [86014da0] LyoPronto v0.3.2 `..`
  [1914dd2f] MacroTools v0.5.16
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.4
  [2e0e35c7] Moshi v0.3.7
  [46d2c3a1] MuladdMacro v0.2.4
  [d41bc354] NLSolversBase v8.0.0
  [77ba4419] NaNMath v1.1.3
  [8913a72c] NonlinearSolve v4.16.0
  [be0214bd] NonlinearSolveBase v2.15.0
  [5959db7a] NonlinearSolveFirstOrder v2.0.0
  [9a2c21bd] NonlinearSolveQuasiNewton v1.12.0
  [26075421] NonlinearSolveSpectralMethods v1.6.0
  [429524aa] Optim v2.0.1
⌃ [bca83a33] OptimizationBase v5.0.0
⌃ [36348300] OptimizationOptimJL v0.4.10
  [bac558e1] OrderedCollections v1.8.1
⌃ [bbf590c4] OrdinaryDiffEqCore v3.17.0
  [4302a76b] OrdinaryDiffEqDifferentiation v2.2.1
  [127b3ac7] OrdinaryDiffEqNonlinearSolve v1.23.0
  [43230ef6] OrdinaryDiffEqRosenbrock v1.25.0
  [90014a1f] PDMats v0.11.37
  [f517fe37] Polyester v0.7.19
  [1d0040c9] PolyesterWeave v0.2.2
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v1.1.2
  [aea7be01] PrecompileTools v1.3.3
  [21216c6a] Preferences v1.5.2
  [08abe8d2] PrettyTables v3.2.3
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.48.0
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.1
⌃ [295af30f] Revise v3.13.2 [loaded: v3.14.0]
  [f2b01f46] Roots v2.2.13
  [7e49a35a] RuntimeGeneratedFunctions v0.5.17
  [94e857df] SIMDTypes v0.1.0
  [c4bf5708] SavitzkyGolay v0.9.1
⌃ [0bca4576] SciMLBase v2.149.0
  [19f34311] SciMLJacobianOperators v0.1.12
  [a6db7da4] SciMLLogging v1.9.1
  [c0aeaf25] SciMLOperators v1.15.1
  [431bcebd] SciMLPublic v1.0.1
  [53ae85a6] SciMLStructures v1.10.0
  [efcf1570] Setfield v1.1.2
  [727e6d20] SimpleNonlinearSolve v2.11.0
  [9f842d2f] SparseConnectivityTracer v1.2.1
⌃ [0a514795] SparseMatrixColorings v0.4.24
  [276daf66] SpecialFunctions v2.7.1
  [03a91e81] SplitApplyCombine v1.2.3
  [aedffcd0] Static v1.3.1
  [0d7ed370] StaticArrayInterface v1.9.0
⌃ [90137ffa] StaticArrays v1.9.17
  [1e83bf80] StaticArraysCore v1.4.4
  [10745b16] Statistics v1.11.1
  [7792a7ef] StrideArraysCore v0.5.8
  [892a3eda] StringManipulation v0.4.4
  [2efcf032] SymbolicIndexingInterface v0.3.46
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.1
  [8290d209] ThreadingUtilities v0.5.5
  [a759f4b9] TimerOutputs v0.5.29
  [84d833dd] TransformVariables v0.8.21
  [781d530d] TruncatedStacktraces v1.4.0
  [9d95f2ec] TypedTables v1.4.6
  [1986cc42] Unitful v1.28.0
  [1d5cc7b8] IntelOpenMP_jll v2025.2.0+0
  [856f044c] MKL_jll v2025.2.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [1317d2d5] oneTBB_jll v2022.0.0+1
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.7.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [ac6e5ff7] JuliaSyntaxHighlighting v1.12.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.12.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [ca575930] NetworkOptions v1.3.0
  [44cfe95a] Pkg v1.12.0
  [de0858da] Printf v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.12.0
  [f489334b] StyledStrings v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.3.0+1
  [deac9b47] LibCURL_jll v8.15.0+0
  [e37daf67] LibGit2_jll v1.9.0+0
  [29816b5a] LibSSH2_jll v1.11.3+1
  [14a3606d] MozillaCACerts_jll v2025.5.20
  [4536629a] OpenBLAS_jll v0.3.29+0
  [05823500] OpenLibm_jll v0.8.7+0
  [458c3c95] OpenSSL_jll v3.5.4+0
  [bea87d4a] SuiteSparse_jll v7.8.3+2
  [83775a58] Zlib_jll v1.3.1+2
  [8e850b90] libblastrampoline_jll v5.15.0+0
  [8e850ede] nghttp2_jll v1.64.0+1
  [3f19e933] p7zip_jll v17.7.0+0
```

  - Output of `versioninfo()`

```julia
Julia Version 1.12.2
Commit ca9b6662be (2025-11-20 16:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, tigerlake)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_CONDAPKG_BACKEND = Null
  JULIA_PYTHONCALL_EXE = C:\Users\iwheeler\Miniconda3\python.exe

```

**Additional context**

Manifest from last successful CI: 
```
[47edcb42] ADTypes v1.21.0
  [7d9f7c33] Accessors v0.1.43
  [79e6a3ab] Adapt v4.4.0
  [4c88cf16] Aqua v0.8.14
  [dce04be8] ArgCheck v2.5.0
  [4fba245c] ArrayInterface v7.22.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [70df07ce] BracketingNonlinearSolve v1.7.0
  [2a0fbf3d] CPUSummary v0.2.7
  [d360d2e6] ChainRulesCore v1.26.0
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [da1fd8a2] CodeTracking v3.0.0
  [3da002f7] ColorTypes v0.12.1
  [38540f10] CommonSolve v0.2.6
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.18.1
  [807dbc54] Compiler v0.1.1
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.6.0
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [82cc6244] DataInterpolations v8.9.0
  [864edb3b] DataStructures v0.19.3
  [e2d170a0] DataValueInterfaces v1.0.0
  [85a47980] Dictionaries v0.4.6
  [2b5f629d] DiffEqBase v6.203.0
  [459566f4] DiffEqCallbacks v4.12.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.7.16
  [ffbed154] DocStringExtensions v0.9.5
  [4e289a0a] EnumX v1.0.6
  [f151be2c] EnzymeCore v0.8.18
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7034ab61] FastBroadcast v0.3.5
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.7.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [ac6e5ff7] JuliaSyntaxHighlighting v1.12.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.12.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [ca575930] NetworkOptions v1.3.0
  [44cfe95a] Pkg v1.12.1
  [de0858da] Printf v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.12.0
  [f489334b] StyledStrings v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.3.0+1
  [deac9b47] LibCURL_jll v8.15.0+0
  [e37daf67] LibGit2_jll v1.9.0+0
  [29816b5a] LibSSH2_jll v1.11.3+1
  [14a3606d] MozillaCACerts_jll v2025.11.4
  [4536629a] OpenBLAS_jll v0.3.29+0
  [05823500] OpenLibm_jll v0.8.7+0
  [458c3c95] OpenSSL_jll v3.5.4+0
  [bea87d4a] SuiteSparse_jll v7.8.3+2
  [83775a58] Zlib_jll v1.3.1+2
  [8e850b90] libblastrampoline_jll v5.15.0+0
  [8e850ede] nghttp2_jll v1.64.0+1
  [3f19e933] p7zip_jll v17.7.0+0
```

### PR DESCRIPTION
**Pull request by Ickaser**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API
  
## Additional context
Fixes #3157. 
The BrownFullBasic initialization solves a nonlinear problem only for the _algebraic_ variables, so if the ODEProblem has chunksize larger than the number of algebraic problems, the initialization needs to pick a smaller chunksize. 

As it stands, this PR fixes the error, but the initialization for out-of-place problems runs into a new error I'm less confident about solving:

```
ERROR: TypeError: in setfield!, expected Vector{Float64}, got a value of type SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}
Stacktrace:
  [1] setproperty!(cache::LinearSolve.LinearCache{…}, name::Symbol, x::SubArray{…})
    @ LinearSolve C:\Users\iwheeler\.julia\packages\LinearSolve\LKo1P\src\common.jl:158
  [2] (::NonlinearSolveBase.LinearSolveJLCache{…})(; A::Matrix{…}, b::SubArray{…}, linu::Vector{…}, reuse_A_if_factorization::Bool, kwargs::@Kwargs{…})
    @ NonlinearSolveBaseLinearSolveExt C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\ext\NonlinearSolveBaseLinearSolveExt.jl:21
  [3] solve!(cache::NonlinearSolveBase.NewtonDescentCache{…}, J::Matrix{…}, fu::SubArray{…}, u::Vector{…}, idx::Val{…}; skip_solve::Bool, new_jacobian::Bool, kwargs::@Kwargs{…})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\descent\newton.jl:120
  [4] step!(cache::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithmCache{…}; recompute_jacobian::Nothing)
    @ NonlinearSolveFirstOrder C:\Users\iwheeler\.julia\packages\NonlinearSolveFirstOrder\hAPzw\src\solve.jl:297
  [5] step!(cache::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithmCache{…})
    @ NonlinearSolveFirstOrder C:\Users\iwheeler\.julia\packages\NonlinearSolveFirstOrder\hAPzw\src\solve.jl:269
  [6] #step!#179
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:634 [inlined]
  [7] step!
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:628 [inlined]
  [8] solve!(cache::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithmCache{…})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:314
  [9] __solve(::NonlinearProblem{…}, ::NonlinearSolveFirstOrder.GeneralizedFirstOrderAlgorithm{…}; kwargs::@Kwargs{…})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:300
 [10] __solve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:291 [inlined]
 [11] macro expansion
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:548 [inlined]
 [12] __generated_polysolve(::NonlinearProblem{…}, ::NonlinearSolveBase.NonlinearSolvePolyAlgorithm{…}; stats::SciMLBase.NLStats, alias::SciMLBase.NonlinearAliasSpecifier, verbose::NonlinearSolveBase.NonlinearVerbosity{…}, initializealg::NonlinearSolveBase.NonlinearSolveDefaultInit, kwargs::@Kwargs{})
    @ NonlinearSolveBase C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:485
 [13] __generated_polysolve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:485 [inlined]
 [14] #__solve#165
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:453 [inlined]
 [15] __solve
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:449 [inlined]
 [16] #solve_call#149
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:174 [inlined]
 [17] solve_call
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:140 [inlined]
 [18] #solve_up#148
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:135 [inlined]
 [19] solve_up
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:120 [inlined]
 [20] #solve#147
    @ C:\Users\iwheeler\.julia\packages\NonlinearSolveBase\Rw8Vf\src\solve.jl:92 [inlined]
 [21] _initialize_dae!(integrator::OrdinaryDiffEqCore.ODEIntegrator{…}, prob::ODEProblem{…}, alg::BrownFullBasicInit{…}, isinplace::Val{…})
    @ OrdinaryDiffEqNonlinearSolve C:\Users\iwheeler\.julia\dev\OrdinaryDiffEq\lib\OrdinaryDiffEqNonlinearSolve\src\initialize_dae.jl:705
 [22] initialize_dae! (repeats 2 times)
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\initialize_dae.jl:20 [inlined]
 [23] _ode_init(prob::ODEProblem{…}, alg::Rodas5P{…}, timeseries_init::Tuple{}, ts_init::Tuple{}, ks_init::Tuple{}; saveat::Tuple{}, tstops::Tuple{}, d_discontinuities::Tuple{}, save_idxs::Nothing, save_everystep::Bool, save_on::Bool, save_discretes::Bool, save_start::Bool, save_end::Nothing, callback::Nothing, dense::Bool, calck::Bool, dt::Nothing, dtmin::Float64, dtmax::Float64, force_dtmin::Bool, adaptive::Bool, abstol::Nothing, reltol::Nothing, gamma::Nothing, qmin::Nothing, qmax::Nothing, qsteady_min::Nothing, qsteady_max::Nothing, beta1::Nothing, beta2::Nothing, qoldinit::Nothing, fullnormalize::Bool, failfactor::Int64, maxiters::Int64, internalnorm::typeof(DiffEqBase.ODE_DEFAULT_NORM), internalopnorm::typeof(LinearAlgebra.opnorm), isoutofdomain::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), unstable_check::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), verbose::SciMLLogging.Standard, controller::Nothing, timeseries_errors::Bool, dense_errors::Bool, advance_to_tstop::Bool, stop_at_next_tstop::Bool, initialize_save::Bool, progress::Bool, progress_steps::Int64, progress_name::String, progress_message::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), progress_id::Symbol, userdata::Nothing, allow_extrapolation::Bool, initialize_integrator::Bool, alias::ODEAliasSpecifier, initializealg::BrownFullBasicInit{…}, rng::Nothing, save_noise::Bool, delta::Nothing, W::Nothing, P::Nothing, sqdt::Nothing, noise::Nothing, c::Nothing, rate_constants::Nothing, _cache::Nothing, _u::Nothing, _uprev::Nothing, seed::UInt64, kwargs::@Kwargs{})
    @ OrdinaryDiffEqCore C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:770
 [24] _ode_init
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:47 [inlined]
 [25] #__init#59
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:37 [inlined]
 [26] __init (repeats 2 times)
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:19 [inlined]
 [27] #__solve#58
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:9 [inlined]
 [28] __solve
    @ C:\Users\iwheeler\.julia\packages\OrdinaryDiffEqCore\mNgXc\src\solve.jl:1 [inlined]
 [29] #solve_call#22
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:172 [inlined]
 [30] solve_call
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:137 [inlined]
 [31] solve_up(prob::ODEProblem{…}, sensealg::Nothing, u0::Vector{…}, p::SciMLBase.NullParameters, args::Rodas5P{…}; originator::SciMLBase.ChainRulesOriginator, kwargs::@Kwargs{…})
    @ DiffEqBase C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:630
 [32] solve_up
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:603 [inlined]
 [33] #solve#28
    @ C:\Users\iwheeler\.julia\packages\DiffEqBase\XLzeg\src\solve.jl:587 [inlined]
 [34] top-level scope
    @ REPL[22]:1
 [35] top-level scope
    @ REPL:1
Some type information was truncated. Use `show(err)` to see complete types.
```

which I think needs to be solved here somewhere:
https://github.com/SciML/OrdinaryDiffEq.jl/blob/6359ecae94193ca2d9ee407ee5de9653aae1e708/lib/OrdinaryDiffEqNonlinearSolve/src/initialize_dae.jl#L686-L705

### CODE REVIEW

**Comment by Ickaser** [comment]
The current (erroring) behavior was introduced in https://github.com/SciML/OrdinaryDiffEq.jl/commit/97d91452a1e8e2a121a1a4bdae97cbe415a34154, https://github.com/SciML/OrdinaryDiffEq.jl/pull/3069

**Comment by Ickaser** [comment]
> As it stands, this PR fixes the error, but the initialization for out-of-place problems runs into a new error I'm less confident about solving:
> 
> ```
> ERROR: TypeError: in setfield!, expected Vector{Float64}, got a value of type SubArray{Float64, 1, Vector{Float64}, Tuple{Vector{Int64}}, false}
> Stacktrace:
>   [1] setproperty!(cache::LinearSolve.LinearCache{…}, name::Symbol, x::SubArray{…})
>     @ LinearSolve C:\Users\iwheeler\.julia\packages\LinearSolve\LKo1P\src\common.jl:158
> ```

This error can be fixed by removing the `@views` in 
https://github.com/SciML/OrdinaryDiffEq.jl/blob/6359ecae94193ca2d9ee407ee5de9653aae1e708/lib/OrdinaryDiffEqNonlinearSolve/src/initialize_dae.jl#L687-L694
which I did in https://github.com/SciML/OrdinaryDiffEq.jl/pull/3199/commits/99386f54efdd1e183c383ca2dd9c299d528d3038, but I don't know if that could cause allocation problems or anything.

~I also trimmed out an unused variable `alg_u` from the same blocks, which doesn't show up anywhere else.~ did not read that code well, reinserted it

**Comment by Ickaser** [comment]
So far, it seems like the GPU tests are failing with "GPU out of memory". I can imagine that this could be caused by extra allocations in the nonlinear solve?... but if not, they seem unrelated to me.

**Comment by Ickaser** [comment]
The Sparse Algebraic Detection test in OrdinaryDiffEqNonlinearSolve seems RNG-dependent; it failed once for me in local testing but passed the next 5 times without my changing anything.

Unfortunately this means that the new tests I wrote for this didn't run, as they are later in the ODENLS suite. But that test set did pass locally, so I suspect after making the (inevitable?) changes to this PR the tests should run.

**Comment by Ickaser** [comment]
On https://github.com/SciML/OrdinaryDiffEq.jl/pull/3199/commits/1f41a543bf68c3eda184bb78d0727924df4eaf63 tests all passed except the StochasticDiffEqWeak ones which didn't finish, then in subsequent commits I changed some formatting and added a new test and some of the other GPU test suites encountered "internal errors" in CUDA or some such. So I think I would call the testing a success here

Although it would be good to address the chunksize type instability inside initialization, I would prefer to leave that for another time; I need this fix to land before my own CI will start working again.

File: lib/OrdinaryDiffEqNonlinearSolve/src/initialize_dae.jl [hunk 1]
```diff
@@ -673,8 +665,11 @@ function _initialize_dae!(
     if isAD
         chunk = ForwardDiff.pickchunksize(count(algebraic_vars))
         _tmp = dualcache(similar(u0), chunk)
+        nlchunk = Val(chunk)
```
Comment (ChrisRackauckas) [inline lib/OrdinaryDiffEqNonlinearSolve/src/initialize_dae.jl]: making the val path just choose 1 probably makes sense. The init happens so little that it's not going to have a meaningful effect on performance overall, but keeping a fully type stable path improves compilation caching so much that it would be a major latency win.

**Comment by Ickaser** [comment]
For some reason the formatting and SpellCheck CI actions started complaining about files not modified by this PR, so I am counting those as a pass.

I set the chunksize to Val(1) and was able to iron out a few other things hurting the type stability so that the out-of-place initialization is fully inferred. The in-place nonlinear solve for in-place ODE solves still has an instability inside NonlinearSolve. 

I did this all investigating manually with Cthulhu; playing around with `Jet.@report_opt`, these changes definitely improved things, but there are other reported problems (some in Base?) so I really don't know how to set up a proper test.

I tried expanding on the MWE of #3157 to check initialization inference like
```julia
integrator = @inferred init(prob, Rodas5(autodiff = AutoForwardDiff(chunksize = 3)))
@inferred SciMLBase.initialize_dae!(integrator)
```
but this comes back false positive since the integrator can be fully inferred without the initialization being inferred.

As noted previously in #2701, the `ODEFunction` constructor defaults to `FullSpecialize`, in which case inference requires a user-specified chunksize.

**Comment by ChrisRackauckas** [comment]
The nonlinearsolve one is https://github.com/SciML/NonlinearSolve.jl/pull/870

**Comment by Ickaser** [comment]
Is there something else you would like to see in this PR before merging?

**Comment by ChrisRackauckas** [comment]
It looks like some other inference tests now pass https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/23355817242/job/67946331674?pr=3199#step:7:962 so those tests should be changed from broken, and rebase so that format check should be passing, and it I think it's good to go.

**Comment by Ickaser** [comment]
The now-passing inference tests in OrdinaryDiffEqBDF were doing something weird and hacky to programmatically check which solvers were type unstable, which seemed to me like it will mask the test results we actually want:
https://github.com/SciML/OrdinaryDiffEq.jl/blob/249cda3241550024de421401bbe0720802e9b3b2/lib/OrdinaryDiffEqBDF/test/jet.jl#L45-L56
 A couple SBDF solvers (IMEXEuler, IMEXEulerARK) were in the wrong list, and those test failures were being hidden by the above hack.

In https://github.com/SciML/OrdinaryDiffEq.jl/pull/3199/commits/f3573067c3737d5efcf5fe91113afabbcf329283 I replaced this with a manual list of which solvers are passing the tests because that will not mask any new passes the same way. I'm open to suggestions on this. Tests should be passing there now. I went ahead and borrowed this same structure to set up some (currently broken) inference tests with `JET.@test_opt` on the DAE initialization, which I hope will give something for Claude to work at.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/NonlinearSolve.jl/pull/870 probably throws a wrench in this in a second, because it looks like the oddness with initialization was due to this upstream instability, but this looks good to go.
